#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_WORKDIR = Path(__file__).resolve().parent / "out"


class QuickstartError(RuntimeError):
    pass


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run the Kino quickstart CLI loop with tiny generated media.")
    parser.add_argument("--workdir", type=Path, default=DEFAULT_WORKDIR, help="Directory for generated quickstart files.")
    parser.add_argument("--python", default=sys.executable, help="Python executable used for kino CLI subprocesses.")
    parser.add_argument("--preset", default="landscape-web", help="Export preset to pass to export-variant and validate-export.")
    parser.add_argument(
        "--skip-media-generation",
        action="store_true",
        help="Reuse existing base.mp4 and assets/cutaway.png instead of generating them with ffmpeg.",
    )
    args = parser.parse_args(argv)

    try:
        outputs = run_quickstart(
            args.workdir,
            python=args.python,
            repo_root=REPO_ROOT,
            preset=args.preset,
            generate_media=not args.skip_media_generation,
        )
    except QuickstartError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print("Kino quickstart complete")
    for label, path in outputs.items():
        print(f"{label}: {path}")
    return 0


def run_quickstart(
    workdir: Path,
    *,
    python: str = sys.executable,
    repo_root: Path = REPO_ROOT,
    preset: str = "landscape-web",
    generate_media: bool = True,
) -> dict[str, Path]:
    workdir = workdir.resolve()
    repo_root = repo_root.resolve()
    assets_dir = workdir / "assets"
    frames_dir = workdir / "verify_frames"
    workdir.mkdir(parents=True, exist_ok=True)
    assets_dir.mkdir(parents=True, exist_ok=True)

    paths = {
        "transcript": workdir / "transcript.json",
        "edit": workdir / "KINO-EDIT.json",
        "manifest": workdir / "KINO-MANIFEST.json",
        "base": workdir / "base.mp4",
        "asset": assets_dir / "cutaway.png",
        "render": workdir / "rendered.mp4",
        "render_receipt": workdir / "KINO-RENDER.json",
        "contact_sheet": workdir / "KINO-CONTACT-SHEET.jpg",
        "frame_qc_json": workdir / "KINO-FRAME-QC.json",
        "frame_qc_md": workdir / "KINO-FRAME-QC.md",
        "audio_qc_json": workdir / "KINO-AUDIO-QC.json",
        "audio_qc_md": workdir / "KINO-AUDIO-QC.md",
        "export": workdir / f"export.{preset}.mp4",
        "validation_json": workdir / "KINO-VALIDATION.json",
        "validation_md": workdir / "KINO-VALIDATION.md",
        "verify_frames": frames_dir,
    }

    _require_tools("ffmpeg", "ffprobe")
    if generate_media:
        _generate_media(paths["base"], paths["asset"])

    _write_transcript(paths["transcript"])

    env = _cli_env(repo_root)
    _require_python_modules(python, env, "PIL")
    _run_cli(python, ["init-edit", "transcript.json", "KINO-EDIT.json", "--id", "quickstart-edit"], workdir, env)
    _run_cli(
        python,
        [
            "add-source",
            "KINO-EDIT.json",
            "src.generated",
            "generated",
            "ffmpeg:lavfi",
            "--title",
            "Generated quickstart media",
            "--license",
            "local test asset",
        ],
        workdir,
        env,
    )
    _run_cli(
        python,
        [
            "add-asset",
            "KINO-EDIT.json",
            "asset.cutaway",
            "src.generated",
            "still",
            "assets/cutaway.png",
            "--width",
            "320",
            "--height",
            "180",
            "--credit",
            "Generated by examples/quickstart/run.py",
        ],
        workdir,
        env,
    )
    _run_cli(
        python,
        [
            "propose-beat",
            "KINO-EDIT.json",
            "beat.cutaway",
            "0",
            "4",
            "--route",
            "generated-source",
            "--interpretation",
            "Show a generated visual cutaway during the opening words.",
            "--source-plan",
            "Use the local generated cutaway still.",
            "--source-id",
            "src.generated",
            "--asset-id",
            "asset.cutaway",
        ],
        workdir,
        env,
    )
    _run_cli(python, ["approve-beat", "KINO-EDIT.json", "beat.cutaway", "asset.cutaway"], workdir, env)
    _run_cli(
        python,
        [
            "propose-beat",
            "KINO-EDIT.json",
            "beat.rejected",
            "1",
            "4",
            "--route",
            "taste",
            "--interpretation",
            "A second visual idea kept as rejected planning history.",
            "--source-plan",
            "Do not render this in the quickstart.",
        ],
        workdir,
        env,
    )
    _run_cli(
        python,
        [
            "reject-beat",
            "KINO-EDIT.json",
            "beat.rejected",
            "Rejected to demonstrate preserved planning history.",
        ],
        workdir,
        env,
    )
    _run_cli(
        python,
        [
            "compile-manifest",
            "KINO-EDIT.json",
            "KINO-MANIFEST.json",
            "--base",
            "base.mp4",
            "--output",
            "rendered.mp4",
            "--size",
            "320x180",
            "--fps",
            "30",
        ],
        workdir,
        env,
    )
    _run_cli(python, ["render-cutaways", "KINO-MANIFEST.json"], workdir, env)
    _run_cli(python, ["verify-frames", "KINO-MANIFEST.json", "--out-dir", "verify_frames"], workdir, env)
    _run_cli(python, ["make-contact-sheet", "verify_frames", "KINO-CONTACT-SHEET.jpg"], workdir, env)
    _run_cli(
        python,
        [
            "check-frames",
            "verify_frames",
            "--manifest",
            "KINO-MANIFEST.json",
            "--json-out",
            "KINO-FRAME-QC.json",
            "--md-out",
            "KINO-FRAME-QC.md",
            "--contact-sheet",
            "KINO-CONTACT-SHEET.jpg",
        ],
        workdir,
        env,
    )
    _run_cli(
        python,
        [
            "analyze-audio",
            "rendered.mp4",
            "--json-out",
            "KINO-AUDIO-QC.json",
            "--md-out",
            "KINO-AUDIO-QC.md",
            "--strict",
        ],
        workdir,
        env,
    )
    _run_cli(
        python,
        ["export-variant", "rendered.mp4", paths["export"].name, "--preset", preset, "--crf", "28"],
        workdir,
        env,
    )
    _run_cli(
        python,
        [
            "validate-export",
            paths["export"].name,
            "--preset",
            preset,
            "--json-out",
            "KINO-VALIDATION.json",
            "--md-out",
            "KINO-VALIDATION.md",
            "--strict",
        ],
        workdir,
        env,
    )
    return paths


def _generate_media(base: Path, asset: Path) -> None:
    _run(
        [
            "ffmpeg",
            "-y",
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=320x180:rate=30:duration=1.2",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=880:sample_rate=48000:duration=1.2",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-movflags",
            "+faststart",
            str(base),
        ],
        cwd=base.parent,
    )
    _run(
        [
            "ffmpeg",
            "-y",
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "color=c=0x1f6feb:s=320x180:d=0.1",
            "-frames:v",
            "1",
            str(asset),
        ],
        cwd=asset.parent,
    )


def _write_transcript(path: Path) -> None:
    path.write_text(
        json.dumps(
            {
                "id": "quickstart-transcript",
                "language": "en",
                "source": "base.mp4",
                "words": [
                    {"id": "w001", "text": "Kino", "start": 0.0, "end": 0.18},
                    {"id": "w002", "text": "quickstart", "start": 0.18, "end": 0.42},
                    {"id": "w003", "text": "renders", "start": 0.42, "end": 0.66},
                    {"id": "w004", "text": "cutaways", "start": 0.66, "end": 0.9},
                ],
            },
            indent=2,
        )
        + "\n"
    )


def _run_cli(python: str, args: list[str], cwd: Path, env: dict[str, str]) -> None:
    _run([python, "-m", "kino.cli", *args], cwd=cwd, env=env)


def _run(command: list[str], *, cwd: Path, env: dict[str, str] | None = None) -> None:
    result = subprocess.run(command, cwd=cwd, env=env, capture_output=True, text=True)
    if result.returncode:
        detail = result.stderr.strip() or result.stdout.strip()
        raise QuickstartError(f"{' '.join(command)} failed: {detail}")


def _cli_env(repo_root: Path) -> dict[str, str]:
    env = os.environ.copy()
    src = str(repo_root / "src")
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = src if not existing else os.pathsep.join([src, existing])
    return env


def _require_tools(*tools: str) -> None:
    missing = [tool for tool in tools if shutil.which(tool) is None]
    if missing:
        raise QuickstartError(f"missing required tool(s): {', '.join(missing)}")


def _require_python_modules(python: str, env: dict[str, str], *modules: str) -> None:
    missing: list[str] = []
    for module in modules:
        result = subprocess.run(
            [python, "-c", f"import {module}"],
            env=env,
            capture_output=True,
            text=True,
        )
        if result.returncode:
            missing.append(module)
    if missing:
        raise QuickstartError(
            f"missing required Python module(s) for {python}: {', '.join(missing)}. "
            'Run pip install -e ".[dev]" or pass --python pointing at an environment with Kino dependencies.'
        )


if __name__ == "__main__":
    raise SystemExit(main())
